### ISSUE TITLE
【java.lang.NullPointerException】checkTransaction

### ISSUE THREAD

**Issue by KernalHelen** [Midtrans/midtrans-java#21] opened 2022-12-11 07:30 UTC
![image](https://user-images.githubusercontent.com/117925358/206891522-5f73282a-4714-4562-bdb0-efd960963d82.png)
![image](https://user-images.githubusercontent.com/117925358/206891536-35917677-0a95-49ac-b4f9-2706c195cb7f.png)
A null pointer exception will be generated, causing the interface unavailable

**Comment by Xaxxis** [comment] 2022-12-12 03:59
Hi @KernalHelen thank you for reaching out to us, could you help to share step by step, how you can reproduce the NPE on checkTransaction method? so we can get a clear explanation here. 

Thanks

**Comment by KernalHelen** [comment] 2022-12-12 09:27
> Hi @KernalHelen thank you for reaching out to us, could you help to share step by step, how you can reproduce the NPE on checkTransaction method? so we can get a clear explanation here.
> 
> Thanks

In the second image, the requestBody is directly empty

**Comment by Xaxxis** [comment] 2022-12-13 02:43
Hi @KernalHelen did you try this on your side? Did you face NPE on checkTransaction method?

Because JSONObject already has a null save [here](https://github.com/stleary/JSON-java/blob/master/src/main/java/org/json/JSONObject.java#L282) so when JSONObject receives null from requestBody it will not reproduce NPE.

thank you

**Comment by rizdaprasetya** [comment] 2022-12-14 07:48
Thanks for reaching out, however the issue you mentioned is a bit unclear for us to understand.

From what we can see, there's also already a `test` scenario covering it as well here:
https://github.com/Midtrans/midtrans-java/blob/1e01a95e0d1a48b43ed324605dc4130e25acb2bf/library/src/test/java/com/midtrans/java/TransactionApiTest.java#L37-L43

So, we are not sure if the issue that you mentioned can practically occurs.

If you still think the issue is valid, please do provide clearer: 
- evidence, like a implementation example. 
- Or how did you encounter this?
- Or scenario to reproduce.
- Or your code & the output log.
- etc.

We'd be happy to check if it valid. 
Otherwise, @Xaxxis  mark this Github issue as `invalid` and close it. Thanks

**Closed as completed** 2022-12-16 07:17 UTC
Labels: invalid
